
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: shan007
logging:
  level:
    root: warn
    com.shy: info
  file:
    name: F:\basic-code\myblog\log\blog-pro.log
